-- CAUTION: THIS SCRIPT DROPS ALL DATA IN YOUR DATABASE!
DROP SCHEMA public CASCADE;
DROP SCHEMA tiger CASCADE;
DROP SCHEMA tiger_data CASCADE;
DROP SCHEMA topology CASCADE;

CREATE SCHEMA public;
CREATE ROLE admin;